### ISSUE TITLE
Clicking "Share Page with *" in dropdown of toolbar button does nothing in Nightly

### ISSUE THREAD

**Issue by masayuki-nakano** [asamuzaK/shareSNS#10]
In this a couple of weeks, "Share Page with *" in the dropdown of toolbar button does not work. However, same UI in context menu still works. I'm not sure exact version what I use because of no information in Add-ons Manager, but I reinstalled from AMO and still reproduce this bug.

**Comment by asamuzaK** [comment]
Thanks for the report.
v2.1.3 will be released soon.
