### ISSUE TITLE
"Share Page with Twitter" does not put link into the tweet box

### ISSUE THREAD

**Issue by masayuki-nakano** [asamuzaK/shareSNS#18]
Starting from (at least) a couple of days ago, "Share Page with Twitter" only puts page's title to tweet box. The opened URL by this addon still has `url=`, but it follows page title and `&amp%3B`. If I modify `&amp%3B` to `&`, I see what expected result.

**Comment by masayuki-nakano** [comment]
I use Firefox Nightly on Windows.

**Comment by asamuzaK** [comment]
Confirmed
