### ISSUE TITLE
Add Pleroma

### ISSUE THREAD

**Issue by asakura42** [asamuzaK/shareSNS#22]
Pls add Pleroma

**Comment by asamuzaK** [comment]
Is format to post like this?

```
https://<mydomain>/share?message=<title>%20<url_link>
```

Ref https://foss-notes.blog.nomagic.uk/2019/11/social-sharing-buttons/

**Comment by asamuzaK** [comment]
[Try build](https://github.com/asamuzaK/shareSNS/tree/pleroma/dest)

I don't have a Pleroma account, so please check yourself and tell me if it works or not.

**Comment by asakura42** [comment]
Yes, it works. But it seems you don't need to replace characters with percent-encoding ones.

**Comment by asamuzaK** [comment]
[2nd try build](https://github.com/asamuzaK/shareSNS/tree/pleroma/dest)

Please try.

**Comment by asakura42** [comment]
@asamuzaK Yep! It works! Thank you :3
